# ?????? ??? ??????
org.gradle.jvmargs=-Xmx2G

# ????????? Fabric ??? 1.21.1
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.5

# ?????? ?????? ????
mod_version=1.0.0
maven_group=com.mr_lisick
archives_base_name=NoGhostBlock

# ?????? Fabric API ??? 1.21.1
fabric_version=0.102.1+1.21.1